name: Dependency Update Check

on:
  schedule:
    - cron: '0 0 * * MON' # Run every monday at midnight https://crontab.guru/every-monday
  workflow_dispatch:
    logLevel:
      description: 'Log level'
      required: true
      default: 'warning'
      type: choice
      options:
        - info
        - warning
        - debug

env:
  NODE_VERSION: 18
  RETENTION_DAYS: 30

jobs:
  cli-dependency-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}
      - run: npm ci
      - name: Check for outdated dependencies in CLI
        run: npm run cli:dependency-check
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: update-check
          path: update-check/
          retention-days: ${{env.RETENTION_DAYS}}
