name: Run Lint

on:
  pull_request:
    branches: [master, develop]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 19
      - run: npm ci
      - run: npm run cli:lint
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: lint-report
          path: lint-report/
          retention-days: 30
